### ISSUE TITLE
1.13.2 permission tab-complete issue

### ISSUE THREAD

**Issue by LogGits** [AcmeProject/WildernessTp#31]
Tabcomplete shows commands, regardless of if a player has permission in 1.13.2. It can be resolved by modifying the plugin.yml to include permissions, for example:
```yaml
commands:
  start:
    description: hub of important commands.
    aliases: info
    permission: test.start

permissions:
  test.start:
    description: give access to /start
    default: op
```
players without access to `test.start`, wont see /start in their tab-complete suggestion list.
