### ISSUE TITLE
Suggestion: Ability to set Min/MaxXY per world

### ISSUE THREAD

**Issue by analogged** [AcmeProject/WildernessTp#86]
Currently when you set Min/MaxXY in the config the plugin will use these limits in the overworld, end, and nether. 

Suggestion: 
Ability to set Min/MaxXY to different values per world. 
The plugin does respect the worldboarder if they are different however I would like to be able to set these to different values for the following example:

Overworld, Nether, and End all have a world boarder of +/- 20k
I would like to set the Wild MaxXY to 20k in the overworld, but only 5k in the Nether and End while leaving the nether and end wordlboarders set to 20k.

**Comment by RoboMWM** [comment]
Mind giving an example of an example config with multiworld limits?

**Comment by analogged** [comment]
Sure how about something like this:

```
Worldlimits:
  Server_overworld:
    MinXY: -20000
    MaxXY: 20000
  Server_nether:
    MinXY: 5000
    MaxXY: 5000
  Server_the_end:
    MinXY: -5000
    MaxXY: 5000
```

**Comment by RoboMWM** [comment]
Look like that works - but what about those who don't care about per-world limits and want a global limit?

**Comment by analogged** [comment]
How about then changing the orginal one to `default` then using world names if you dont want default. 
Something like this:

```
Worldlimits:
  Global_limit:
    MinXY: -20000
    MaxXY: 20000
  #Server_nether:
    #MinXY: 5000
    #MaxXY: 5000
 # Server_the_end:
    #MinXY: -5000
    #MaxXY: 5000
```

Then in the default config you can leave them commented out and only use the global limit while also making it clear for those who wish to use seperate values.
